unix {
    SFDIR = SoftFloat-3c/source
    #INCLUDEPATH += $$PWD/$$SFDIR $$PWD/$$SFDIR/8086-SSE $$PWD/$$SFDIR/include
    INCLUDEPATH += $$PWD/$$SFDIR/include
    #DEFINES += SOFTFLOAT_FAST_INT64 SOFTFLOAT_ROUND_ODD INLINE_LEVEL=5 SOFTFLOAT_FAST_DIV32TO16 SOFTFLOAT_FAST_DIV64TO32
    DEFINES += LITTLEENDIAN=1  # FIXME for big endian platforms ...
    DEFINES += QSOFTFLOAT_LIB
    LIBS += -L$$PWD -lqsoftfloat
}
